name: guidedlayout2_1679
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# flutter:
#   assets:
#     - asset/image.png

# dependencies:
#   flutter:
#     sdk: flutter
#   cached_network_image: ^3.2.0 # Versi terkini
